### ISSUE TITLE
Easy to port?

### ISSUE THREAD

**Issue by Alexey-T** [johncsnyder/SwiftKitten#1]
Hi. Is it easy to port to Cudatext [uvviewsoft.com] ? What is needed, some Swift toolkit?

**Comment by johncsnyder** [comment]
I'm not too familiar with Cudatext, but it should be straightforward I guess. You need to install [SourceKitten](https://github.com/jpsim/SourceKitten) separately. SwiftKitten makes requests to SourceKitten via a python subprocess. SourceKitten does all the hard work. You're welcome to fork and give it a shot.

**Comment by Alexey-T** [comment]
Thanks..
